version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: khaleel
      POSTGRES_PASSWORD: khaleel
      POSTGRES_DB: objectstorage
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: