spring.application.name=objectstorage

#db
spring.datasource.url=jdbc:postgresql://localhost:5432/objectstorage
spring.datasource.username=khaleel
spring.datasource.password=khaleel

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#storage
app.storage.location=storage-data

#error handling
spring.web.error.include-message=always
