spring.application.name=objectstorage

#db
spring.datasource.url=jdbc:postgresql://localhost:5432/objectstorage
spring.datasource.username=khaleel
spring.datasource.password=khaleel

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#storage
app.storage.location=storage-data

#error handling
spring.web.error.include-message=always

#jwt configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
